version: 2.1

jobs:
  test:
    docker:
      - image: node:10.11.0
      - image: mongo:2.6.8
        name: mongodb
    steps:
      - checkout
      - restore_cache:
          keys:
            - bt_core_{{ checksum "package.json" }}
            - bt_core_
      - run:
          name: Test
          command: |
            npm install -g gulp-cli
            npm install
            gulp ci-build
      - save_cache:
          key: bt_core_{{ checksum "package.json" }}
          paths:
            - node_modules/

  deploy-dev:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t bottom-time/core-dev .
      - run:
          name: Deploy Docker Image
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag bottom-time/core-dev:latest 961445962603.dkr.ecr.us-east-1.amazonaws.com/bottom-time/core-dev:latest
            docker push 961445962603.dkr.ecr.us-east-1.amazonaws.com/bottom-time/core-dev:latest

  deploy-prod:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t bottom-time/core .
      - run:
          name: Deploy Docker Image
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker tag bottom-time/core:latest 961445962603.dkr.ecr.us-east-1.amazonaws.com/bottom-time/core:latest
            docker push 961445962603.dkr.ecr.us-east-1.amazonaws.com/bottom-time/core:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only:
                - prod
