version: 2.1

jobs:
  test:
    docker:
      - image: node:10.11.0
      - image: mongo:2.6.8
        name: mongodb
    steps:
      - checkout
      - restore_cache:
          keys:
            - bt_core_{{ checksum "package.json" }}
            - bt_core_
      - run:
          name: Test
          command: |
            npm install -g gulp-cli
            npm install
            gulp ci-build
      - save_cache:
          key: bt_core_{{ checksum "package.json" }}
          paths:
            - node_modules/

  deploy-dev:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: docker build -t bottom-time/core-dev .
      - run:
          name: Get Terraform
          command: |
            wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
            unzip terraform.zip
          working_directory: /usr/bin
      - run:
          command: terraform -v

  deploy-prod:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: docker build -t bottom-time/core .
      - run:
          name: Get Terraform
          command: |
            sudo wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
            sudo unzip terraform.zip
          working_directory: /usr/bin
      - run:
          command: terraform -v

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only:
                - prod
